# Generated by Django 2.2.6 on 2019-10-27 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'ordering': ('-valid_from',), 'verbose_name': '优惠劵', 'verbose_name_plural': '优惠券'},
        ),
    ]
