# Generated by Django 2.2.6 on 2019-10-18 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20191018_2032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-updated',), 'verbose_name': '产品', 'verbose_name_plural': '产品'},
        ),
    ]
